export const data = {
  name: "Fruits Report",
  code: "Egor",
  columns: [
    {
      dataField: "1",
      caption: "Banana",
      dataType: "fruit",
      format: "utf",
      alignment: "left",
    },
    {
      dataField: "2",
      caption: "Apple",
      dataType: "fruit",
      format: "jjj",
      alignment: "right",
    },
    {
      dataField: "3",
      caption: "Orange",
      dataType: "fruit",
      format: "kkk",
      alignment: "center",
    },
    {
      dataField: "4",
      caption: "Lemon",
      dataType: "fruit",
      format: "lll",
      alignment: "left",
    },
    {
      dataField: "5",
      caption: "Mango",
      dataType: "fruit",
      format: "mmm",
      alignment: "center",
    },
    {
      dataField: "6",
      caption: "Pinapple",
      dataType: "fruit",
      format: "ppp",
      alignment: "left",
    },
    {
      dataField: "7",
      caption: "Apricot",
      dataType: "fruit",
      format: "aaa",
      alignment: "right",
    },
    {
      dataField: "8",
      caption: "Avocado",
      dataType: "fruit",
      format: "rrr",
      alignment: "left",
    },{
      dataField: "9",
      caption: "Kiwi",
      dataType: "fruit",
      format: "kkk",
      alignment: "right",
    },
    {
      dataField: "10",
      caption: "Lime",
      dataType: "fruit",
      format: "lll",
      alignment: "left",
    },
    {
      dataField: "11",
      caption: "Nectarine",
      dataType: "fruit",
      format: "utf",
      alignment: "left",
    },
    {
      dataField: "12",
      caption: "Papaya",
      dataType: "fruit",
      format: "jjj",
      alignment: "right",
    },
    {
      dataField: "13",
      caption: "Pessionfruit",
      dataType: "fruit",
      format: "kkk",
      alignment: "center",
    },
    {
      dataField: "14",
      caption: "Peach",
      dataType: "fruit",
      format: "lll",
      alignment: "left",
    },
    {
      dataField: "15",
      caption: "Pear",
      dataType: "fruit",
      format: "mmm",
      alignment: "center",
    },
    {
      dataField: "16",
      caption: "Quence",
      dataType: "fruit",
      format: "ppp",
      alignment: "left",
    },
    {
      dataField: "17",
      caption: "Melon",
      dataType: "fruit",
      format: "aaa",
      alignment: "right",
    },
    {
      dataField: "18",
      caption: "Watermelon",
      dataType: "fruit",
      format: "rrr",
      alignment: "left",
    },{
      dataField: "19",
      caption: "Pomegranat",
      dataType: "fruit",
      format: "rrr",
      alignment: "right",
    },
    {
      dataField: "20",
      caption: "Tamarind",
      dataType: "fruit",
      format: "ttt",
      alignment: "left",
    },
    {
      dataField: "21",
      caption: "Jackfruit",
      dataType: "fruit",
      format: "xxx",
      alignment: "center",
    },{
      dataField: "22",
      caption: "Lichi",
      dataType: "fruit",
      format: "www",
      alignment: "right",
    },
    {
      dataField: "23",
      caption: "Grape",
      dataType: "fruit",
      format: "ggg",
      alignment: "left",
    },
  ],
};
